/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SiteIdRouteImport } from './routes/$siteId'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiDemoRouteImport } from './routes/api/demo'
import { Route as AdminSetupRouteImport } from './routes/admin/setup'
import { Route as AdminLogoutRouteImport } from './routes/admin/logout'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminSiteIdRouteImport } from './routes/admin/$siteId'
import { Route as SiteIdViewerAccessRouteImport } from './routes/$siteId/viewer-access'
import { Route as AdminSetupSubmitRouteImport } from './routes/admin/setup/submit'
import { Route as AdminLoginSubmitRouteImport } from './routes/admin/login/submit'
import { Route as AdminSiteIdSyncRouteImport } from './routes/admin/$siteId/sync'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIdRoute = SiteIdRouteImport.update({
  id: '/$siteId',
  path: '/$siteId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDemoRoute = ApiDemoRouteImport.update({
  id: '/api/demo',
  path: '/api/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSetupRoute = AdminSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogoutRoute = AdminLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSiteIdRoute = AdminSiteIdRouteImport.update({
  id: '/$siteId',
  path: '/$siteId',
  getParentRoute: () => AdminRoute,
} as any)
const SiteIdViewerAccessRoute = SiteIdViewerAccessRouteImport.update({
  id: '/viewer-access',
  path: '/viewer-access',
  getParentRoute: () => SiteIdRoute,
} as any)
const AdminSetupSubmitRoute = AdminSetupSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => AdminSetupRoute,
} as any)
const AdminLoginSubmitRoute = AdminLoginSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => AdminLoginRoute,
} as any)
const AdminSiteIdSyncRoute = AdminSiteIdSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => AdminSiteIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$siteId': typeof SiteIdRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/$siteId/viewer-access': typeof SiteIdViewerAccessRoute
  '/admin/$siteId': typeof AdminSiteIdRouteWithChildren
  '/admin/login': typeof AdminLoginRouteWithChildren
  '/admin/logout': typeof AdminLogoutRoute
  '/admin/setup': typeof AdminSetupRouteWithChildren
  '/api/demo': typeof ApiDemoRoute
  '/api/health': typeof ApiHealthRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/$siteId/sync': typeof AdminSiteIdSyncRoute
  '/admin/login/submit': typeof AdminLoginSubmitRoute
  '/admin/setup/submit': typeof AdminSetupSubmitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$siteId': typeof SiteIdRouteWithChildren
  '/$siteId/viewer-access': typeof SiteIdViewerAccessRoute
  '/admin/$siteId': typeof AdminSiteIdRouteWithChildren
  '/admin/login': typeof AdminLoginRouteWithChildren
  '/admin/logout': typeof AdminLogoutRoute
  '/admin/setup': typeof AdminSetupRouteWithChildren
  '/api/demo': typeof ApiDemoRoute
  '/api/health': typeof ApiHealthRoute
  '/admin': typeof AdminIndexRoute
  '/admin/$siteId/sync': typeof AdminSiteIdSyncRoute
  '/admin/login/submit': typeof AdminLoginSubmitRoute
  '/admin/setup/submit': typeof AdminSetupSubmitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$siteId': typeof SiteIdRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/$siteId/viewer-access': typeof SiteIdViewerAccessRoute
  '/admin/$siteId': typeof AdminSiteIdRouteWithChildren
  '/admin/login': typeof AdminLoginRouteWithChildren
  '/admin/logout': typeof AdminLogoutRoute
  '/admin/setup': typeof AdminSetupRouteWithChildren
  '/api/demo': typeof ApiDemoRoute
  '/api/health': typeof ApiHealthRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/$siteId/sync': typeof AdminSiteIdSyncRoute
  '/admin/login/submit': typeof AdminLoginSubmitRoute
  '/admin/setup/submit': typeof AdminSetupSubmitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$siteId'
    | '/admin'
    | '/$siteId/viewer-access'
    | '/admin/$siteId'
    | '/admin/login'
    | '/admin/logout'
    | '/admin/setup'
    | '/api/demo'
    | '/api/health'
    | '/admin/'
    | '/admin/$siteId/sync'
    | '/admin/login/submit'
    | '/admin/setup/submit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$siteId'
    | '/$siteId/viewer-access'
    | '/admin/$siteId'
    | '/admin/login'
    | '/admin/logout'
    | '/admin/setup'
    | '/api/demo'
    | '/api/health'
    | '/admin'
    | '/admin/$siteId/sync'
    | '/admin/login/submit'
    | '/admin/setup/submit'
  id:
    | '__root__'
    | '/'
    | '/$siteId'
    | '/admin'
    | '/$siteId/viewer-access'
    | '/admin/$siteId'
    | '/admin/login'
    | '/admin/logout'
    | '/admin/setup'
    | '/api/demo'
    | '/api/health'
    | '/admin/'
    | '/admin/$siteId/sync'
    | '/admin/login/submit'
    | '/admin/setup/submit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SiteIdRoute: typeof SiteIdRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  ApiDemoRoute: typeof ApiDemoRoute
  ApiHealthRoute: typeof ApiHealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$siteId': {
      id: '/$siteId'
      path: '/$siteId'
      fullPath: '/$siteId'
      preLoaderRoute: typeof SiteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/demo': {
      id: '/api/demo'
      path: '/api/demo'
      fullPath: '/api/demo'
      preLoaderRoute: typeof ApiDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/setup': {
      id: '/admin/setup'
      path: '/setup'
      fullPath: '/admin/setup'
      preLoaderRoute: typeof AdminSetupRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logout': {
      id: '/admin/logout'
      path: '/logout'
      fullPath: '/admin/logout'
      preLoaderRoute: typeof AdminLogoutRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/$siteId': {
      id: '/admin/$siteId'
      path: '/$siteId'
      fullPath: '/admin/$siteId'
      preLoaderRoute: typeof AdminSiteIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/$siteId/viewer-access': {
      id: '/$siteId/viewer-access'
      path: '/viewer-access'
      fullPath: '/$siteId/viewer-access'
      preLoaderRoute: typeof SiteIdViewerAccessRouteImport
      parentRoute: typeof SiteIdRoute
    }
    '/admin/setup/submit': {
      id: '/admin/setup/submit'
      path: '/submit'
      fullPath: '/admin/setup/submit'
      preLoaderRoute: typeof AdminSetupSubmitRouteImport
      parentRoute: typeof AdminSetupRoute
    }
    '/admin/login/submit': {
      id: '/admin/login/submit'
      path: '/submit'
      fullPath: '/admin/login/submit'
      preLoaderRoute: typeof AdminLoginSubmitRouteImport
      parentRoute: typeof AdminLoginRoute
    }
    '/admin/$siteId/sync': {
      id: '/admin/$siteId/sync'
      path: '/sync'
      fullPath: '/admin/$siteId/sync'
      preLoaderRoute: typeof AdminSiteIdSyncRouteImport
      parentRoute: typeof AdminSiteIdRoute
    }
  }
}

interface SiteIdRouteChildren {
  SiteIdViewerAccessRoute: typeof SiteIdViewerAccessRoute
}

const SiteIdRouteChildren: SiteIdRouteChildren = {
  SiteIdViewerAccessRoute: SiteIdViewerAccessRoute,
}

const SiteIdRouteWithChildren =
  SiteIdRoute._addFileChildren(SiteIdRouteChildren)

interface AdminSiteIdRouteChildren {
  AdminSiteIdSyncRoute: typeof AdminSiteIdSyncRoute
}

const AdminSiteIdRouteChildren: AdminSiteIdRouteChildren = {
  AdminSiteIdSyncRoute: AdminSiteIdSyncRoute,
}

const AdminSiteIdRouteWithChildren = AdminSiteIdRoute._addFileChildren(
  AdminSiteIdRouteChildren,
)

interface AdminLoginRouteChildren {
  AdminLoginSubmitRoute: typeof AdminLoginSubmitRoute
}

const AdminLoginRouteChildren: AdminLoginRouteChildren = {
  AdminLoginSubmitRoute: AdminLoginSubmitRoute,
}

const AdminLoginRouteWithChildren = AdminLoginRoute._addFileChildren(
  AdminLoginRouteChildren,
)

interface AdminSetupRouteChildren {
  AdminSetupSubmitRoute: typeof AdminSetupSubmitRoute
}

const AdminSetupRouteChildren: AdminSetupRouteChildren = {
  AdminSetupSubmitRoute: AdminSetupSubmitRoute,
}

const AdminSetupRouteWithChildren = AdminSetupRoute._addFileChildren(
  AdminSetupRouteChildren,
)

interface AdminRouteChildren {
  AdminSiteIdRoute: typeof AdminSiteIdRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRouteWithChildren
  AdminLogoutRoute: typeof AdminLogoutRoute
  AdminSetupRoute: typeof AdminSetupRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSiteIdRoute: AdminSiteIdRouteWithChildren,
  AdminLoginRoute: AdminLoginRouteWithChildren,
  AdminLogoutRoute: AdminLogoutRoute,
  AdminSetupRoute: AdminSetupRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SiteIdRoute: SiteIdRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  ApiDemoRoute: ApiDemoRoute,
  ApiHealthRoute: ApiHealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
